name: Run Script
on: [push]

jobs:
  tests:
    name: run script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Adzz/jest_test_action@v1.0.0
        with:
          package-manager: npm
          command: update:ci
